# @Author: Yitan Lu
# @Timestamp for Creation: 2023-03-12 11:14:15

# ===========================================================
# Analysis of target density distribution via random sampling
# ===========================================================
# Description:
# This script contains three functions:
# 'computeSeedsTargetDens': This function is used to calculate
# the change in target density as the number of genes increases
# after the seed genes runs restart random walk.
# -----------------------------------------------
# 'sampleRandomSeeds': This function performs random sampling
# which starts with the same target density of the seed genes
# and returns all the sampled results into a matrix.
# -----------------------------------------------
# 'computeDistribution': This function is used to calculate
# the z-distribution and the corresponding p-value
# for the density matrix generated by random sampling.
#
# To use the functions, save the script as a .R file,
# and load it in your R session using the 'source' function,
# for example: source("targetdens_analysis.R")
# ===============================================
# Parameters:
# seedRWR: Obtained using the 'runRWR' function from the DTANetPerturbeR package.
# Net_tars: Obtained using the 'mapTargets' function from the DTANetPerturbeR package.
# ===============================================
# Example usage:
# Calculate the target density
# seed_density <- computeSeedsTargetDens(seedRWR, Net_tars)
# -----------------------------------------------
# Perform random sampling
# random_density <- sampleRandomSeeds(seed_density, seedcount = 80, Net_tars, iter = 100)
# -----------------------------------------------
# Compute the z-score and p-value
# zscore_pvalue <- computeDistribution(random_density, seed_density)
# ===============================================

computeSeedsTargetDens <- function(seedRWR, Net_tars) {
  # Assign "0" to a new column iftar
  seedRWR$iftar <- 0

  # Give value "1" to target genes in iftar
  rownames(seedRWR) <- seedRWR$Gene_Symbol
  net_tars <- Net_tars$Gene_Symbol
  seedRWR[net_tars, 3] <- 1

  # Calculate the cumulative sum of total genes and target genes
  seedRWR$genenum <- 1:nrow(seedRWR)
  seedRWR$tarnum <- cumsum(seedRWR$iftar)

  # Calculate density: the ratio of target gene number to total gene number
  seedRWR$density <- seedRWR$tarnum / seedRWR$genenum

  # Return the calculation result
  seed_tardens <- seedRWR
  return(seed_tardens)
}


sampleRandomSeeds <- function(Seeds_TarDens, seedcount, Net_tars, iter = 100){
  # Extract the number of target and non-target seeds
  seed_tarnum <- Seeds_TarDens[seedcount, 5]
  seed_nontarnum <- seedcount - seed_tarnum

  # Identify non-target genes
  nodes <- seed_tardens$Gene_Symbol
  Net_nontars <- setdiff(nodes, Net_tars[, 1])
  Net_nontars <- as.data.frame(Net_nontars)

  # Initialize a dataframe to store the results
  result <- as.data.frame(matrix(nrow = length(nodes), ncol = iter))

  # Random sampling: calculate gene target density, and store results
  for (i in 1:iter){
    ran_tarnum <- Net_tars[sample(1:nrow(Net_tars), seed_tarnum, replace = F), ]
    ran_nontarnum <- Net_nontars[sample(1:nrow(Net_nontars), seed_nontarnum, replace = F), ]

    # Calculate the RWR scores using the seed set
    ranseed <- union(ran_tarnum, ran_nontarnum)
    ranseed <- as.data.frame(ranseed)
    RWR_score <- runRWR(seeds = ranseed)

    # Save the density for each iteration
    Dens <- computeSeedsTargetDens(RWR_score, Net_tars)
    Dens <- Dens$density
    result[, i] <- Dens
  }

  # Set column names for the result dataframe
  colnames(result) <- paste("sample", 1:iter, sep = "_")
  random_des_df <- result

  # Write the result dataframe to a text file
  write.table(random_des_df,
              paste("Random_", iter, "_Target_Density.txt", sep = ''),
              quote = F, sep = "\t", row.names = F)

  # Return the calculation result
  return(random_des_df)
}


computeDistribution <- function(Des_Mat, Seeds_TarDens) {
  # Add the Seed column containing target density values
  Des_Mat$Seed <- Seeds_TarDens$density

  # Calculate Z-scores and p-values for each observation in 'Des_Mat'
  observation <- Des_Mat$Seed
  zscore <- c()
  for (i in 1:nrow(Des_Mat)){
    distribution <- as.data.frame(t(Des_Mat[i, c(1:100)]))[, 1]
    m <- mean(distribution, na.rm = T)
    sd <- sd(distribution, na.rm = T)
    z <- (observation[i] - m) / sd
    zscore <- c(zscore, z)
  }
  pvalue <- pnorm(zscore, lower.tail = F)

  # Add 'zscore' and 'pvalue' columns to 'Des_Mat'
  Des_Mat$zscore <- zscore
  Des_Mat$pvalue <- pvalue

  # Write the updated 'Des_Mat' to a text file
  write.table(Des_Mat, "Des_Mat_Distribution.txt",
              quote = F, sep = "\t", row.names = F)

  # Return the calculation result
  return(Des_Mat)
}
